spring.application.name=demo

jwt.secret=your-secret-key-here-change-this-in-production-12345678901234567890

spring.datasource.url=jdbc:postgresql://localhost:5432/bookingshare-db
spring.datasource.username=myuser
spring.datasource.password=mypassword
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true